First stage of loading ION 4.1.2 into a branch, for merge into sync branch.

diff --git a/demos/bench-bibect/dotest b/demos/bench-bibect/dotest
--- a/demos/bench-bibect/dotest
+++ b/demos/bench-bibect/dotest
@@ -28,17 +28,16 @@ echo "########################################"
 echo
 pwd | sed "s/\/.*\///" | xargs echo "NAME: "
 echo
-echo "PURPOSE: produce simple throughput benchmark results, for direct
-	comparison among computing platforms running ION.  The test is
-	performed using the BIBE convergence-layer protocol (over UDP/IP)
-	between neighboring nodes residing on the same computer, relying
-	on BIBE custodial retransmission for reliability; bundles received
-	via BIBE are forwarded to the final destination by STCP.  So the
-	results exercise BP and BIBE CT in a non-loopback configuration,
-	over loopback IP; the results are therefore unaffected by network
-	traffic, router performance, or network interface card performance.
-	Since the bundle size exceeds the maximum capacity of a UDP
-	packet, the test exercises BP fragmentation and reassembly as well."
+echo "PURPOSE: produce a demonstration configuration for using the 
+	BIBE convergence-layer protocol (over UDP/IP) between neighboring 
+	DTN nodes, relying on BIBE custodial retransmission for reliability; 
+	bundles received via BIBE are forwarded to the final destination 
+	by STCP. Since the bundle size exceeds the maximum capacity of a UDP
+	packet, the test exercises BP fragmentation and reassembly as well.
+	Due to the inherent unreliability of UDP and the fact the way network
+	subsystem drops UDP data is implementation-dependent, the actual 
+	throughput will vary from system to system. A final note is that the
+	throughput is also a function of the size of the bundle."
 
 echo
 echo "CONFIG: 2 node custom:"
@@ -58,6 +57,14 @@ echo "***PLEASE NOTE: this benchmark test requires Bundle Protocol version 7."
 
 ./cleanup
 sleep 1
+
+echo "Checking for additional memory needed for this demo..."
+./check_memory 
+if [ $? != 0 ]; then
+	echo "Can't run, need additional system resources"
+	exit 1
+fi
+
 echo "Starting ION..."
 export ION_NODE_LIST_DIR=$PWD
 rm -f ./ion_nodes
@@ -73,24 +80,42 @@ cd ../3.bench.bibe
 
 sleep 3
 echo ""
-echo "Test 1: 10 bundles of 1000000 bytes each."
+echo "Test 1: 2000 bundles of 50,000 bytes each."
 cd ../4.bench.bibe
-bpcounter ipn:4.1 10 &
+bpcounter ipn:4.1 2000 &
 BPCOUNTER_PID=$!
 sleep 1
 
+# if bpcounter didn't start, then something went wrong and we definitely haven't passsed!
+# some ps don't like -p syntax, most do.
+if [ "$1" == "windows" ]
+then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+fi
+if [ $RETURN_VALUE -eq 0 ]
+then
+	echo "bpcounter couldn't be started."
+	echo "...benchmarking terminated."
+	exit 1
+fi
+
+
 cd ../2.bench.bibe
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 "Go."
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
-bptrace ipn:2.1 ipn:4.1 dtn:none 15 0.1.0.0.0.13 @bpdriverAduFile
+# send bundle under 64KB to avoid fragmentation
+# over UDPCLO
+
+COUNT=0
+
+while [ $COUNT -le 2001 ]
+do
+
+   bptrace ipn:2.1 ipn:4.1 dtn:none 100 0.1.0.0.0.13 @testfile-50KB
+
+   COUNT=$(($COUNT+1))
+
+done
 
 # Wait for transmission to finish.
 echo "Waiting for transmission to finish..."
@@ -102,7 +127,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ "$1" == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -122,9 +152,9 @@ then
 	echo "Test did not complete."
 fi
 
-echo "Waiting 20 sec for transmission to complete and fragments to expire..."
+echo "Waiting 150 sec for transmission to complete and fragments to expire..."
 
-sleep 20
+sleep 150
 
 echo "...stopping ION..."
 cd ../2.bench.bibe
diff --git a/demos/bench-dgr/dotest b/demos/bench-dgr/dotest
--- a/demos/bench-dgr/dotest
+++ b/demos/bench-dgr/dotest
@@ -47,6 +47,14 @@ echo "########################################"
 
 ./cleanup
 sleep 1
+
+echo "Checking for additional memory needed for this demo..."
+./check_memory 
+if [ $? != 0 ]; then
+	echo "Can't run, need additional system resources"
+	exit 1
+fi
+
 echo "Starting ION..."
 export ION_NODE_LIST_DIR=$PWD
 rm -f ./ion_nodes
@@ -66,6 +74,21 @@ bpcounter ipn:3.1 10000 &
 BPCOUNTER_PID=$!
 sleep 1
 
+# if bpcounter didn't start, then something went wrong and we definitely haven't passsed!
+# some ps don't like -p syntax, most do.
+if [ $1 == "windows" ]
+then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+fi
+if [ $RETURN_VALUE -eq 0 ]
+then
+	echo "bpcounter couldn't be started."
+	echo "...benchmarking terminated."
+	exit 1
+fi
+
 cd ../2.bench.dgr
 bpdriver 10000 ipn:2.1 ipn:3.1 -1000 &
 
@@ -79,7 +102,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -129,7 +157,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -179,7 +212,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -229,7 +267,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -279,7 +322,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -329,7 +377,12 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
@@ -367,7 +420,7 @@ BPCOUNTER_PID=$!
 sleep 1
 
 cd ../2.bench.dgr
-bpdriver 1 ipn:2.1 ipn:3.1 -1000000000 &
+bpdriver 1 ipn:2.1 ipn:3.1 -1000000000 t900 &
 
 #Wait for transmission to finish.
 echo "Waiting for transmission to finish..."
@@ -379,13 +432,18 @@ do
 	sleep 1
 	echo "...receiving..."
 	# some ps don't like -p syntax, most do.
-	ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	if [ $1 == "windows" ]
+	then
+		ps | grep "$BPCOUNTER_PID" >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	else
+		ps $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || ps -p $BPCOUNTER_PID >& /dev/null && RETURN_VALUE=1 || RETURN_VALUE=0
+	fi
 	if [ $RETURN_VALUE -eq 0 ]
 	then
 		echo "...transmission finished."
 		RUNNING=0
 	fi
-	if [ $TIMER -gt 300 ]
+	if [ $TIMER -gt 900 ]
 	then
 		#infinite loop protection
 		echo "...5 minutes passed; giving up."
